{% set name = "google-cloud-redis" %}
{% set version = "2.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c5aaf6dbdf8bb1425bd42ef482a6c0ecc4b4d1718d49267d510799015c6ff1d2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - google-api-core-grpc >=1.26.0,<3.0.0dev
    - packaging >=14.3
    - proto-plus >=1.4.0

test:
  imports:
    - grpc
    - google.cloud.redis
    - google.cloud.redis_v1
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/googleapis/python-redis
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Google Cloud Memorystore for Redis API client library
  description: "Google Cloud Memorystore for Redis API is a Google Cloud service that lets client applications communicate with a fully managed Redis service for Google Cloud. Applications running on Google Cloud can achieve extreme performance by leveraging the highly scalable, available, secure Redis service without the\
    \ burden of managing complex Redis deployments.\nSee the [quick start guide](https://googleapis.dev/python/redis/latest/index.html#quick-start)."

  doc_url: https://googleapis.dev/python/redis/latest/index.html
  dev_url: https://github.com/googleapis/python-redis

extra:
  recipe-maintainers:
    - parthea
    - xylar
